name: warehouse_optimizer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - plotly
  - scipy
  - networkx
  - pip:
    - numpy
    - tqdm


